entero numero,suma
inicio
escriba "ingrese valor *Numero*"
lea numero
llamar nueva_linea
escriba "ingrese valor *Suma*"
lea suma
escriba "______________"
llamar nueva_linea
Mientras (numero <= 10) Haga
llamar obtener_caracter
escriba "numero ",numero
llamar nueva_linea
suma <- suma + numero
numero <- numero + 1
escriba "suma ", suma
llamar nueva_linea
escriba "______________"
llamar nueva_linea
Fin Mientras
escriba "suma total: ", suma,"  numero total: ", numero
fin